# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501

import typing

__all__ = [
    "WebullHistoricalClient",
]

@typing.final
class WebullHistoricalClient:
    def __init__(
        self,
        api_key: str,
        api_secret: str,
        access_token: str | None = None,
        base_url: str | None = None,
    ) -> None: ...
    def get_history_bars(
        self,
        symbol: str,
        category: str,
        timespan: str,
        start_ms: int,
        end_ms: int,
        trading_sessions: str | None = None,
        venue: str | None = None,
        price_precision: int = 2,
    ) -> typing.Any: ...
    def get_snapshot(self, symbols: typing.Sequence[str], category: str) -> typing.Any: ...
    def get_ticks(
        self, symbol: str, category: str, end_ms: int, count: int = 200
    ) -> typing.Any: ...
